### ISSUE TITLE
data preprocessing for lidar 

### ISSUE THREAD

**Issue by szhang963** [VISION-SJTU/Lightning-NeRF#3]
Hi, I am very interested in your great work. 

Could you share the script of data preprocessing in argoverse v2 dataset, especially with the point cloud processing.

Thanks in advance.

**Comment by XJay18** [comment]
Hi, we followed the [official repository](https://github.com/argoverse/av2-api) of `av2-api` for data preprocessing. FYI only, I also uploaded our implemented preprocessing scripts [here](https://drive.google.com/file/d/1FvDp_AyugRIMvIzrN7_JaEdq3eMVkjb6/view?usp=sharing).

(Note that I currently do not have access to the raw data of the argoverse2 dataset since I have left the internship institution and the raw data is stored in their server. The uploaded scripts are my personal backup.)

**Comment by szhang963** [comment]
Thanks very much.
